### PR TITLE
Avoid overloading `kind` attribute to mark snips as draft

### PR DESCRIPTION
**Pull request by floehopper**
I'm pretty sure the only effect of marking a snip as draft is to not include it in the the lists of links to snips generated by the `list-of` snip.

This commit introduces a new `draft` attribute to mark snips as draft instead of overloading the `kind` attribute. Snips with the `draft` attribute set to `true` will be excluded from lists of links to snips generated by the `list-of` snip.

The benefit of this approach is that other code can *rely* on the `kind` attribute always being meaningful even when the snip is in the "draft" state.

I've also updated the Rake tasks and corresponding templates to work with the new approach.

I think that snips in directories with a leading underscore (e.g. "soups/blog/_drafts") are not available in the "soup", but for consistency I have marked them as draft anyway.

### CODE REVIEW

**Comment by floehopper** [comment]
I'm hoping that this PR will make the 3rd commit in #39 unnecessary.

@chrisroos: Please could you review. My only real uncertainty is whether there was any other implicit behaviour which relied on the old `:kind: draft` mechanism.

**Comment by chrisroos** [comment]
I think it might be worth updating the README, which currently states:

> The flip side is that if you want to keep a post as a 'draft', just omit that property, or set it to something else. Maybe `draft`; it doesn't matter.

Aside from my minor suggestion, this all looks good to me, @floehopper.

**Comment by floehopper** [comment]
> I think it might be worth updating the README

Thanks - I've updated the README and amended the commit.

**Comment by floehopper** [comment]
Manually merged.

**Pull request merged**
