### PR TITLE
Provide links back to S&T index page and other recent S&T event pages

### PR DESCRIPTION
**Pull request by floehopper**
Trello card: https://trello.com/c/IlpqXRkl

These commits introduce rather more duplication that I would like, but I couldn't see a better way of doing things.

### CODE REVIEW

**Comment by chrisroos** [comment]
@floehopper: I get the following error when trying to view the draft show-and-tell pages (e.g. show-and-tell-27) in this branch:

```
NoMethodError: undefined method `name' for nil:NilClass
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:102:in `render_without_including_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:87:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:70:in `block in render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:122:in `rendering_and_handling_errors'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:69:in `render'
	/Users/chrisroos/Code/freerange/site/lib/blog_renderer.rb:20:in `process_text'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:99:in `render_without_including_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:87:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:70:in `block in render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:122:in `rendering_and_handling_errors'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:69:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:63:in `block in include_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:52:in `gsub'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:52:in `include_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:88:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:70:in `block in render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:122:in `rendering_and_handling_errors'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:69:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:63:in `block in include_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:52:in `gsub'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:52:in `include_snips'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/renderers/base.rb:88:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:70:in `block in render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:122:in `rendering_and_handling_errors'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:69:in `render'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:140:in `render_in_format'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/app.rb:45:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/vanilla-2.0.0.beta/lib/vanilla/static.rb:18:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/chrisroos/.rbenv/versions/2.2.5/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
::1 - - [08/Dec/2016:10:05:47 +0000] "GET /show-and-tell-27 HTTP/1.1" 500 129132 0.1475
```

**Comment by floehopper** [comment]
Hmm - I must've done something silly. I'll investigate.

**Comment by chrisroos** [comment]
Aside from the problem mentioned above I think this all looks good. I agree that the duplication isn't ideal but I think it's OK for now.

**Comment by floehopper** [comment]
I've just added another commit which fixes the problem, but I'm not very happy with it. I'm going to have a quick look at introducing a new `draft` attribute to avoid overloading the `kind` attribute.

**Comment by floehopper** [comment]
Having merged #41 I was able to remove the 3rd commit [1], thus simplifying the code. I've also rebased against master and force-pushed in preparation for merging.

[1]: 51041746dc6a1521d4bf79da7842a4057c9d9aa1

**Pull request merged**
